### ISSUE TITLE
Can HDT suggestions be returned incrementally?

### ISSUE THREAD

**Issue by wouterbeek** [JanWielemaker/hdt4swipl#2]
Is it possible to change `hdt_suggestions/5` so that it non-deterministically enumerates all results?  Alternatively, could it return a lazy list?

Sometimes there are very many terms with the same prefix and then the `Length` has to be set to increasingly large values.

**Comment by JanWielemaker** [comment]
It won't really help as the low-level interface wants a `max_count` and returns an array, so one first needs a low-level API that creates an iterator of some sort rather than collecting all the suggestions as an array of strings.

**Comment by wouterbeek** [comment]
@JanWielemaker Thanks for the info, I'm opening an issue at `hdt-cpp`.
