### ISSUE TITLE
Non-deterministic implementation of `hdt_suggestions`

### ISSUE THREAD

**Issue by wouterbeek** [JanWielemaker/hdt4swipl#3]
In commit 8a3ea90bf787937504b9e7c747537e272328829f I tried to use the new, iterator-based implementation for retrieving suggestions.  When I compile I get the following error, but `handle` is used at other places in the same file (including earlier positions) and then the compiler does not complain:

```
ERROR: c/hdt4pl.cpp: In function 'foreign_t pl_hdt_suggestions__4(PlTermv)':
ERROR: c/hdt4pl.cpp:434:29: error: 'handle' was not declared in this scope
ERROR:    switch(PL_foreign_control(handle))
```

How does `handle` work in this file?

PS: This commit assumes that the `develop` branch of hdt-cpp is used.

**Comment by JanWielemaker** [comment]
You need `PREDICATE_NONDET` to declare the predicate
