### ISSUE TITLE
Predicate `hdt_string_id/4' does not deal with Unicode correctly

### ISSUE THREAD

**Issue by wouterbeek** [JanWielemaker/hdt4swipl#4]
Predicate `hdt_string_id/4` does not deal with Unicode characters correctly.  As an MWE take the following N-Triples file:

```n-triples
<x:x> <y:y> "宇宙"@ja .
```

When used with the current version on master, we get the following result:

```prolog
?- test.
"å®å®"@ja
```

Predicate `tets/0` is implemented as follows:

```prolog
:- use_module(library(hdt)).

test :-
  hdt_create_from_file('test.hdt', 'test.nt', []),
  setup_call_cleanup(
    hdt_open(Hdt, 'test.hdt'),
    (
      hdt_string_id(Hdt, object, String, 1),
      format(user_output, "~s\n", [String])
    ),
    hdt_close(Hdt)
  ).
```

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with e0a0eff87fc3318434cb493690c570e1255ed30e
