### ISSUE TITLE
Should HDT be used as of 2022?

### ISSUE THREAD

**Issue by erikkaplun** [JanWielemaker/hdt4swipl#7]
For non mission-critical stuff, is this pack usable in practice?
How likely is it that it will be further enhanced in the future?

**Comment by JanWielemaker** [comment]
HDTs have quite unique features in the sense that they allow pretty fast access to huge triple sets with limited resources.   The academic project seems to be sleeping.   Some companies use HDTs and have extended the infrastructure for them.   

All in all, the source is out there and likely continues to work for quite a while.  There is no reason not to use it if it solves your problems.   It is unclear whether further enhancements will ever be available.
